# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

source  'https://user.googlesource.com/wilkinsonclay/specs'                                        
source 'https://github.com/CocoaPods/Specs.git'                                 

pod 'GooglePlayGames', '~> 5.0'
