# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

source  'https://team.googlesource.com/gswitch/internal-specs'                                        
source 'https://github.com/CocoaPods/Specs.git'

pod 'GooglePlayGames', '~> 5.0'

