# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

pod 'GooglePlayGames', '~> 5.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
